version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:cached
      - ./Test Data:/Test Data:ro
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://familycare:familycare@postgres:5432/familycare
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: familycare
      POSTGRES_PASSWORD: familycare
      POSTGRES_DB: familycare
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U familycare"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  postgres_data: