version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:cached
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  mcp-server:
    build: ./mcp-server
    container_name: mcp-server
    ports:
      - "8888:8888"
    environment:
      - BACKEND_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend