"""create upcoming_appointments table

Revision ID: 2a1a3c094490
Revises: 001_initial
Create Date: 2025-10-04 09:14:16.160245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_upcoming'
down_revision: str = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcoming_appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nfz_id', sa.String(length=255), nullable=False),
    sa.Column('place', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('benefit', sa.String(length=500), nullable=False),
    sa.Column('waiting_people', sa.Integer(), nullable=False),
    sa.Column('average_wait_days', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfz_id')
    )
    op.drop_index('idx_parsed_appointments_date', table_name='parsed_appointments')
    op.drop_index('idx_parsed_appointments_status', table_name='parsed_appointments')
    op.drop_index('idx_parsed_appointments_type', table_name='parsed_appointments')
    op.drop_table_comment(
        'parsed_appointments',
        existing_comment='Stores parsed appointment data extracted from uploaded PDF medical documents',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'parsed_appointments',
        'Stores parsed appointment data extracted from uploaded PDF medical documents',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_parsed_appointments_type', 'parsed_appointments', ['appointment_type'], unique=False)
    op.create_index('idx_parsed_appointments_status', 'parsed_appointments', ['processing_status'], unique=False)
    op.create_index('idx_parsed_appointments_date', 'parsed_appointments', ['date'], unique=False)
    op.drop_table('upcoming_appointments')
    # ### end Alembic commands ###
